#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           fRCtrl,        tmotorVex393_HBridge, PIDControl, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port2,           fRDrive,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           bRCtrl,        tmotorVex393_MC29, PIDControl, encoderPort, I2C_2)
#pragma config(Motor,  port4,           bRDrive,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           bLCtrl,        tmotorVex393_MC29, PIDControl, encoderPort, I2C_3)
#pragma config(Motor,  port8,           bLDrive,       tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           fLDrive,       tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port10,          fLCtrl,        tmotorVex393_HBridge, PIDControl, encoderPort, I2C_4)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define PID_DRIVE_MAX 127
#define PID_DRIVE_MIN -127

// magic numbers from tons of experiment
float  pid_Kp = 0.5;
float  pid_Ki = 0.0001;
float  pid_Kd = 0.5;

static bool pidRunning = true;
static float pidRequestedValue = 0.0;
//static float pidRequestedValueL = 0.0;

void clearAllEnc()
{
	resetMotorEncoder(motor[fLCtrl]);
	resetMotorEncoder(motor[bLCtrl]);
	resetMotorEncoder(motor[fRCtrl]);
	resetMotorEncoder(motor[bRCtrl]);
}

task pidControllerFL()
{
	float  pidSensorCurrentValue;
	float  pidError;
	float  pidLastError;

	float  pidIntegral;
	float  pidDerivative;
	float  pidDrive;
	//clear all encoders !
	clearAllEnc();
	//init
	pidLastError = 0;
	pidIntegral = 0;

	//looping >_<
	while(true)
	{
		if(pidRunning)
		{
			pidSensorCurrentValue = SensorValue[I2C_4];
			pidError =  pidRequestedValue - pidSensorCurrentValue;
			// important here above

			if(pid_Ki != 0)
			{
				// shall we have a limit???
				if(abs(pidError) < 50)
					pidIntegral = pidIntegral + pidError;
				else
					pidIntegral = 0;
			}
			else
				pidIntegral = 0;

			// derivative
			pidDerivative = pidError - pidLastError;
			pidLastError = pidError;

			// outputs
			pidDrive = (pid_Kp * pidError) + (pid_Ki * pidIntegral) + (pid_Kd * pidDerivative);

			// limit drive
			if(pidDrive > PID_DRIVE_MAX ) pidDrive = PID_DRIVE_MAX;
			else if(pidDrive < PID_DRIVE_MIN ) pidDrive = PID_DRIVE_MIN;

			motor[fLCtrl] = pidDrive;
		}
		else
		{
			pidError      = 0;
			pidLastError  = 0;
			pidIntegral   = 0;
			pidDerivative = 0;
			motor[fLCtrl] = 0;
		}
		wait1Msec(25);
	}
}

task pidControllerBR()
{
	float  pidSensorCurrentValue;
	float  pidError;
	float  pidLastError;

	float  pidIntegral;
	float  pidDerivative;
	float  pidDrive;
	//clear all encoders !
	clearAllEnc();
	//init
	pidLastError = 0;
	pidIntegral = 0;

	//looping >_<
	while(true)
	{
		if(pidRunning)
		{
			pidSensorCurrentValue = SensorValue[I2C_2];
			pidError =  pidRequestedValue - pidSensorCurrentValue;
			// important here above

			if(pid_Ki != 0)
			{
				// shall we have a limit???
				if(abs(pidError) < 50)
					pidIntegral = pidIntegral + pidError;
				else
					pidIntegral = 0;
			}
			else
				pidIntegral = 0;

			// derivative
			pidDerivative = pidError - pidLastError;
			pidLastError = pidError;

			// outputs
			pidDrive = (pid_Kp * pidError) + (pid_Ki * pidIntegral) + (pid_Kd * pidDerivative);

			// limit drive
			if(pidDrive > PID_DRIVE_MAX ) pidDrive = PID_DRIVE_MAX;
			else if(pidDrive < PID_DRIVE_MIN ) pidDrive = PID_DRIVE_MIN;

			motor[bRCtrl] = pidDrive;
		}
		else
		{
			pidError      = 0;
			pidLastError  = 0;
			pidIntegral   = 0;
			pidDerivative = 0;
			motor[bRCtrl] = 0;
		}
		wait1Msec(25);
	}
}

task pidControllerBL()
{
	float  pidSensorCurrentValue;
	float  pidError;
	float  pidLastError;

	float  pidIntegral;
	float  pidDerivative;
	float  pidDrive;
	//clear all encoders !
	clearAllEnc();
	//init
	pidLastError = 0;
	pidIntegral = 0;

	//looping >_<
	while(true)
	{
		if(pidRunning)
		{
			pidSensorCurrentValue = SensorValue[I2C_3];
			pidError =  pidRequestedValue - pidSensorCurrentValue;
			// important here above

			if(pid_Ki != 0)
			{
				// shall we have a limit???
				if(abs(pidError) < 50)
					pidIntegral = pidIntegral + pidError;
				else
					pidIntegral = 0;
			}
			else
				pidIntegral = 0;

			// derivative
			pidDerivative = pidError - pidLastError;
			pidLastError = pidError;

			// outputs
			pidDrive = (pid_Kp * pidError) + (pid_Ki * pidIntegral) + (pid_Kd * pidDerivative);

			// limit drive
			if(pidDrive > PID_DRIVE_MAX ) pidDrive = PID_DRIVE_MAX;
			else if(pidDrive < PID_DRIVE_MIN ) pidDrive = PID_DRIVE_MIN;

			motor[bLCtrl] = pidDrive;
		}
		else
		{
			pidError      = 0;
			pidLastError  = 0;
			pidIntegral   = 0;
			pidDerivative = 0;
			motor[bLCtrl] = 0;
		}
		wait1Msec(25);
	}
}

task main()
{
	startTask(pidControllerFL);
	startTask(pidControllerBR);
	startTask(pidControllerBL);
	while(true)
	{
		motor[fRCtrl] = -vexRT[Ch1];
		//motor[bLCtrl] = vexRT[Ch4];

		pidRequestedValue = SensorValue[I2C_1]; // master right
		//pidRequestedValueL = SensorValue[I2C_3]; // master left

		if(vexRT[Btn6U] == 1){
			motor[fRDrive] = 127;
			motor[bRDrive] = 127;
		}
		else if(vexRT[Btn6D] == 1){
			motor[fRDrive] = -127;
			motor[bRDrive] = -127;
		}
		else if(vexRT[Btn6U] == 0 && vexRT[Btn6D] == 0){
			motor[fRDrive] = 0;
			motor[bRDrive] = 0;
		}

		if(vexRT[Btn5U] == 1){
			motor[fLDrive] = 127;
			motor[bLDrive] = 127;
		}
		else if(vexRT[Btn5D] == 1){
			motor[fLDrive] = -127;
			motor[bLDrive] = -127;
		}
		else if(vexRT[Btn5U] == 0 && vexRT[Btn5D] == 0){
			motor[fLDrive] = 0;
			motor[bLDrive] = 0;
		}
	}
	wait1Msec(25);
}
